const diccionario = {
    "Afar": "aa",
    "Abjaso": "ab",
    "Achenés": "ace",
    "Acholi": "ach",
    "Adangme": "ada",
    "Afrikáans": "af",
    "Afrihili": "afh",
    "Acano": "aka",
    "Acadio": "akk",
    "Aleutiano": "ale",
    "Amárico": "am",
    "Aragonés": "an",
    "Inglés antiguo": "ang",
    "Árabe": "ar",
    "Arameo": "arc",
    "Árabe najdi": "ars",
    "Mapuche": "arn",
    "Arapaho": "arp",
    "Artificial": "art",
    "Arawak": "arw",
    "Asamés": "as",
    "Asturiano": "ast",
    "Avar": "ava",
    "Avéstico": "ave",
    "Awadhi": "awa",
    "Aimara": "ay",
    "Azerí": "az",
    "Baskir": "ba",
    "Baluchi": "bal",
    "Bambara": "bam",
    "Balinés": "ban",
    "Basa": "bas",
    "Bielorruso": "be",
    "Beya": "bej",
    "Bemba": "bem",
    "Búlgaro": "bg",
    "Bihari": "bh",
    "Bhojpuri": "bho",
    "Bislama": "bi",
    "Bicolano": "bik",
    "Edo": "bin",
    "Pie negro": "bla",
    "Bengalí": "bn",
    "Tibetano": "bo",
    "Bretón": "br",
    "Brijbhasha": "bra",
    "Bosnio": "bs",
    "Buriato": "bua",
    "Buguinés": "bug",
    "Catalán": "ca",
    "Caddo": "cad",
    "Taíno": "car",
    "Cebuano": "ceb",
    "Chamorro": "ch",
    "Chamorro": "cha",
    "Chibcha": "chb",
    "Checheno": "che",
    "Chagatay": "chg",
    "Mari": "chm",
    "Mandarín": "cmn",
    "Choctaw": "cho",
    "Cheroqui": "chr",
    "Eslavo eclesiástico antiguo": "chu",
    "Chuvasio": "chv",
    "Cheyene": "chy",
    "Corso": "co",
    "Cree": "cr",
    "Copto": "cop",
    "Córnico": "cor",
    "Tártaro de Crimea": "crh",
    "Cree": "cre",
    "Checo": "cs",
    "Casubio": "csb",
    "Galés": "cy",
    "Danés": "da",
    "Dakota": "dak",
    "Alemán": "de",
    "Delaware": "del",
    "Dinka": "din",
    "Diriku": "diu",
    "Dhivehi": "div",
    "Dogri": "doi",
    "Duala": "dua",
    "Neerlandés medio": "dum",
    "Diula": "dyu",
    "Dzongkha": "dz",
    "Efik": "efi",
    "Egipcio antiguo": "egy",
    "Acayo": "eka",
    "Griego": "el",
    "Elamita": "elx",
    "Inglés": "en",
    "Inglés medio": "enm",
    "Esperanto": "eo",
    "Español": "es",
    "Lengua de señas de Estonia": "eso",
    "Estonio": "et",
    "Euskera": "eu",
    "Ewe": "ewe",
    "Ewondo": "ewo",
    "Persa": "fa",
    "Fang": "fan",
    "Fante": "fat",
    "Finés": "fi",
    "Fiyiano": "fj",
    "Feroés": "fo",
    "Francés": "fr",
    "Francés medio": "frm",
    "Francés antiguo": "fro",
    "Fula": "ful",
    "Friulano": "fur",
    "Frisón": "fy",
    "Irlandés": "ga",
    "Ga": "gaa",
    "Gayo": "gay",
    "Gaélico escocés": "gd",
    "Yehén": "gez",
    "Kiribasiano": "gil",
    "Gallego": "gl",
    "Alemán medio": "gmh",
    "Guaraní": "gn",
    "Alemán antiguo": "goh",
    "Gondi": "gon",
    "Gótico": "got",
    "Grebo": "grb",
    "Griego antiguo": "grc",
    "Guyaratí": "gu",
    "Manés": "gv",
    "Hausa": "ha",
    "Haida": "hai",
    "Hawaiano": "haw",
    "Hebreo": "he",
    "Herero": "her",
    "Hindi": "hi",
    "Hiligainón": "hil",
    "Hiri motu": "hmo",
    "Croata": "hr",
    "Húngaro": "hu",
    "Hupa": "hup",
    "Armenio": "hy",
    "Interlingua": "ia",
    "Dayaco": "iba",
    "Plantilla:ibo": "ibo",
    "Indonesio": "id",
    "Occidental": "ie",
    "Lolo de Sichuán": "ii",
    "Inupiaq": "ik",
    "Ilocano": "ilo",
    "Ido": "io",
    "Islandés": "is",
    "Italiano": "it",
    "Inuktitut": "iu",
    "Japonés": "ja",
    "Judeopersa": "jpr",
    "Judeoárabe": "jrb",
    "Javanés": "jv",
    "Georgiano": "ka",
    "Karakalpako": "kaa",
    "Cabil": "kab",
    "Kachín": "kac",
    "Kikamba": "kam",
    "Plantilla:kau": "kau",
    "Cavi": "kaw",
    "Jasí": "kha",
    "Jotanés": "kho",
    "Plantilla:kik": "kik",
    "Kazajo": "kk",
    "Groenlandés": "kl",
    "Camboyano": "km",
    "Kannada": "kn",
    "Coreano": "ko",
    "Konkani": "kok",
    "Plantilla:kom": "kom",
    "Plantilla:kon": "kon",
    "Kosraeano": "kos",
    "Kpelle": "kpe",
    "Curuj": "kru",
    "Cachemiro": "ks",
    "Kurdo": "ku",
    "Plantilla:kua": "kua",
    "Kumyko": "kum",
    "Kusaal": "kus",
    "Kutenai": "kut",
    "Komi": "kv",
    "Córnico": "kw",
    "Kirguís": "ky",
    "Latín": "la",
    "Judeoespañol": "lad",
    "Landi": "lah",
    "Lamba": "lam",
    "Luxemburgués": "lb",
    "Lesguiano": "lez",
    "Limburgués": "li",
    "Lingala": "ln",
    "Lao": "lo",
    "Lituano": "lt",
    "Letón": "lv",
    "Moksha": "mdf",
    "Maorí": "mi",
    "Macedonio": "mk",
    "Malayalam": "ml",
    "Mongol": "mn",
    "Manchú": "mnc",
    "Moldavo": "mo",
    "Maratí": "mr",
    "Malayo": "ms",
    "Maltés": "mt",
    "Birmano": "my",
    "Erzya": "myv",
    "Nauruano": "na",
    "Náhuatl (realmente es de ISO 639-2 pero la fundación Wikimedia lo usa)": "nah",
    "Napolitano": "nap",
    "Plantilla:nav": "nav",
    "Noruego bokmål": "nb",
    "Nepalés": "ne",
    "Sindebele": "nd",
    "Bajo alemán": "nds",
    "Bajo sajón neerlandés": "nds",
    "Ndonga": "ng",
    "Neerlandés": "nl",
    "Noruego nynorsk": "nn",
    "Noruego bokmål": "no",
    "Nrebele": "nr",
    "Navajo": "nv",
    "Chewa": "ny",
    "Occitano": "oc",
    "Ojibwe": "oj",
    "Oromo": "om",
    "Oriya": "or",
    "Oseta": "os",
    "Papiamento": "pap",
    "Pali": "pi",
    "Polaco": "pl",
    "Pastún": "ps",
    "Portugués": "pt",
    "Quechua": "qu",
    "Rapa nui": "rap",
    "Kirundi": "rn",
    "Rumano": "ro",
    "Ruso": "ru",
    "Ruandés": "rw",
    "Sánscrito": "sa",
    "Sardo": "sc",
    "Escocés": "sco",
    "Sindhi": "sd",
    "Cingalés": "si",
    "Sami septentrional": "se",
    "Eslovaco": "sk",
    "Esloveno": "sl",
    "Samoano": "sm",
    "Sami inari": "smn",
    "Shona": "sn",
    "Somalí": "so",
    "Albanés": "sq",
    "Serbio": "sr",
    "Swazi": "ss",
    "Sundanés": "su",
    "Sueco": "sv",
    "Swahili": "sw",
    "Tamil": "ta",
    "Telugú": "te",
    "Tayiko": "tg",
    "Tailandés": "th",
    "Tigriña": "ti",
    "Turcomano": "tk",
    "Tagalo": "tl",
    "Klingon": "tlh",
    "Setsuana": "tn",
    "Tongano": "to",
    "Tok pisin": "tpi",
    "Turco": "tr",
    "Xitsonga": "ts",
    "Tártaro": "tt",
    "Twi": "tw",
    "Udmurto": "udm",
    "Uigur": "ug",
    "Ucraniano": "uk",
    "Urdu": "ur",
    "Uzbeco": "uz",
    "Luvenda": "ve",
    "Vietnamita": "vi",
    "Volapuk": "vo",
    "Votio": "vot",
    "Valón": "wa",
    "Wolof": "wo",
    "Xhosa": "xh",
    "Yídish": "yi",
    "Yoruba": "yo",
    "Maya yucateco": "yua",
    "Cantonés": "yue",
    "Chuan": "za",
    "Mandarín": "zh",
    "Zulú": "zu"
}

module.exports = diccionario;